[2021-08-28 10:53:41,164] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test.training_model_A 2021-08-27T00:00:00+00:00 [queued]>
[2021-08-28 10:53:41,167] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: test.training_model_A 2021-08-27T00:00:00+00:00 [queued]>
[2021-08-28 10:53:41,167] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-28 10:53:41,167] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-28 10:53:41,167] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-28 10:53:41,186] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): training_model_A> on 2021-08-27T00:00:00+00:00
[2021-08-28 10:53:41,187] {standard_task_runner.py:52} INFO - Started process 1340 to run task
[2021-08-28 10:53:41,188] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'training_model_A', '2021-08-27T00:00:00+00:00', '--job-id', '71', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/example.py', '--cfg-path', '/tmp/tmpx_utmhju', '--error-file', '/tmp/tmptbkwhct0']
[2021-08-28 10:53:41,188] {standard_task_runner.py:77} INFO - Job 71: Subtask training_model_A
[2021-08-28 10:53:41,238] {logging_mixin.py:104} INFO - Running <TaskInstance: test.training_model_A 2021-08-27T00:00:00+00:00 [running]> on host DESKTOP-4B4VMOV.localdomain
[2021-08-28 10:53:41,282] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=training_model_A
AIRFLOW_CTX_EXECUTION_DATE=2021-08-27T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-27T00:00:00+00:00
[2021-08-28 10:53:41,283] {python.py:151} INFO - Done. Returned value was: 8
[2021-08-28 10:53:41,318] {taskinstance.py:1204} INFO - Marking task as SUCCESS. dag_id=test, task_id=training_model_A, execution_date=20210827T000000, start_date=20210828T085341, end_date=20210828T085341
[2021-08-28 10:53:41,332] {taskinstance.py:1265} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-08-28 10:53:41,360] {local_task_job.py:149} INFO - Task exited with return code 0
