[2021-07-19 19:43:34,631] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: scrape_nasdaq_ftp.nasdaq_symbols 2021-07-19T17:43:32.438285+00:00 [queued]>
[2021-07-19 19:43:34,636] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: scrape_nasdaq_ftp.nasdaq_symbols 2021-07-19T17:43:32.438285+00:00 [queued]>
[2021-07-19 19:43:34,637] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 19:43:34,637] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-07-19 19:43:34,637] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-07-19 19:43:34,662] {taskinstance.py:1107} INFO - Executing <Task(PythonOperator): nasdaq_symbols> on 2021-07-19T17:43:32.438285+00:00
[2021-07-19 19:43:34,664] {standard_task_runner.py:52} INFO - Started process 13739 to run task
[2021-07-19 19:43:34,667] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_nasdaq_ftp', 'nasdaq_symbols', '2021-07-19T17:43:32.438285+00:00', '--job-id', '27', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/nasdaq_dag.py', '--cfg-path', '/tmp/tmpx5wusq_w', '--error-file', '/tmp/tmp53h1q8_3']
[2021-07-19 19:43:34,668] {standard_task_runner.py:77} INFO - Job 27: Subtask nasdaq_symbols
[2021-07-19 19:43:34,696] {logging_mixin.py:104} INFO - Running <TaskInstance: scrape_nasdaq_ftp.nasdaq_symbols 2021-07-19T17:43:32.438285+00:00 [running]> on host DESKTOP-4B4VMOV.localdomain
[2021-07-19 19:43:34,760] {taskinstance.py:1300} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=scrape_nasdaq_ftp
AIRFLOW_CTX_TASK_ID=nasdaq_symbols
AIRFLOW_CTX_EXECUTION_DATE=2021-07-19T17:43:32.438285+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-07-19T17:43:32.438285+00:00
[2021-07-19 19:43:34,761] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/yaysh/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/yaysh/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/yaysh/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/yaysh/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/python.py", line 150, in execute
    return_value = self.execute_callable()
  File "/home/yaysh/anaconda3/envs/airflow/lib/python3.8/site-packages/airflow/operators/python.py", line 161, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/yaysh/airflow/dags/nasdaq_dag.py", line 23, in download_nasdaq_symbols
    nasdaq_symbol_downloader.download_history()
TypeError: download_history() takes 0 positional arguments but 1 was given
[2021-07-19 19:43:34,762] {taskinstance.py:1544} INFO - Marking task as FAILED. dag_id=scrape_nasdaq_ftp, task_id=nasdaq_symbols, execution_date=20210719T174332, start_date=20210719T174334, end_date=20210719T174334
[2021-07-19 19:43:34,798] {local_task_job.py:149} INFO - Task exited with return code 1
